insert into manufacturer (id, name) values (1, 'Rhycero');
insert into manufacturer (id, name) values (2, 'Zoomcast');
insert into manufacturer (id, name) values (3, 'Ntag');
insert into manufacturer (id, name) values (4, 'Aivee');
insert into manufacturer (id, name) values (5, 'Yozio');
insert into manufacturer (id, name) values (6, 'Flashspan');
insert into manufacturer (id, name) values (7, 'Flipstorm');
insert into manufacturer (id, name) values (8, 'Yoveo');
insert into manufacturer (id, name) values (9, 'Jaloo');
insert into manufacturer (id, name) values (10, 'Browsecat');
insert into manufacturer (id, name) values (11, 'Kanoodle');
insert into manufacturer (id, name) values (12, 'Kayveo');
insert into manufacturer (id, name) values (13, 'Photobean');
insert into manufacturer (id, name) values (14, 'Trilith');
insert into manufacturer (id, name) values (15, 'Voonix');
insert into manufacturer (id, name) values (16, 'Fivechat');
insert into manufacturer (id, name) values (17, 'Tagcat');
insert into manufacturer (id, name) values (18, 'Quamba');
insert into manufacturer (id, name) values (20, 'Zoomlounge');
insert into manufacturer (id, name) values (21, 'Meemm');
insert into manufacturer (id, name) values (22, 'Twitterlist');
insert into manufacturer (id, name) values (23, 'Meezzy');
insert into manufacturer (id, name) values (24, 'Tambee');
insert into manufacturer (id, name) values (25, 'Vitz');
insert into manufacturer (name) values ('Thoughtsphere');
insert into manufacturer (name) values ('Photofeed');
insert into manufacturer (name) values ('Linkbridge');
insert into manufacturer (name) values ('Mynte');
insert into manufacturer (name) values ('Trudoo');
insert into manufacturer (name) values ('Tekfly');
insert into manufacturer (name) values ('Oyoyo');
insert into manufacturer (name) values ('Eire');
insert into manufacturer (name) values ('Edgepulse');
insert into manufacturer (name) values ('Twimbo');
insert into manufacturer (name) values ('Mybuzz');
insert into manufacturer (name) values ('Wikizz');
insert into manufacturer (name) values ('Wordify');
insert into manufacturer (name) values ('Youspan');
insert into manufacturer (name) values ('Trunyx');
insert into manufacturer (name) values ('Layo');
insert into manufacturer (name) values ('Skynoodle');
insert into manufacturer (name) values ('Realcube');
insert into manufacturer (name) values ('Yabox');
insert into manufacturer (name) values ('Skaboo');

insert into category (name) values ('orci');
insert into category (name) values ('vivamus');
insert into category (name) values ('dapibus');
insert into category (name) values ('ac');
insert into category (name) values ('imperdiet');
insert into category (name) values ('nulla nisl');
insert into category (name) values ('posuere cubilia');
insert into category (name) values ('aliquam sit');
insert into category (name) values ('leo maecenas');
insert into category (name) values ('at');
insert into category (name) values ('in');
insert into category (name) values ('rhoncus');
insert into category (name) values ('scelerisque mauris');
insert into category (name) values ('eu');
insert into category (name) values ('consequat morbi');
insert into category (name) values ('sapien placerat');
insert into category (name) values ('ante vel');
insert into category (name) values ('auctor gravida');
insert into category (name) values ('eros');
insert into category (name) values ('justo');
insert into category (name) values ('nullam');
insert into category (name) values ('ipsum primis');
insert into category (name) values ('at ipsum');
insert into category (name) values ('sapien varius');
insert into category (name) values ('congue elementum');
insert into category (name) values ('vulputate elementum');
insert into category (name) values ('viverra');
insert into category (name) values ('est');
insert into category (name) values ('lectus in');
insert into category (name) values ('erat');

insert into subcategory (parent_id) values (5);
insert into subcategory (parent_id) values (5);
insert into subcategory (parent_id) values (3);
insert into subcategory (parent_id) values (11);
insert into subcategory (parent_id) values (8);
insert into subcategory (parent_id) values (7);
insert into subcategory (parent_id) values (27);
insert into subcategory (parent_id) values (7);
insert into subcategory (parent_id) values (25);
insert into subcategory (parent_id) values (26);