.read criar.sql

insert into country (country_name) values ('Israel');
insert into country (country_name) values ('New Zealand');
insert into country (country_name) values ('Indonesia');
insert into country (country_name) values ('China');
insert into country (country_name) values ('Ukraine');
insert into country (country_name) values ('Croatia');
insert into country (country_name) values ('Philippines');
insert into country (country_name) values ('Russia');
insert into country (country_name) values ('Macedonia');
insert into country (country_name) values ('Thailand');
insert into country (country_name) values ('Argentina');
insert into country (country_name) values ('France');
insert into country (country_name) values ('Guatemala');
insert into country (country_name) values ('Mexico');
insert into country (country_name) values ('Zimbabwe');
insert into country (country_name) values ('Qatar');
insert into country (country_name) values ('Vietnam');
insert into country (country_name) values ('Belarus');
insert into country (country_name) values ('Haiti');
insert into country (country_name) values ('Afghanistan');
insert into country (country_name) values ('Canada');
insert into country (country_name) values ('Nigeria');
insert into country (country_name) values ('Czech Republic');
insert into country (country_name) values ('Sweden');
insert into country (country_name) values ('Brazil');
insert into country (country_name) values ('Greece');
insert into country (country_name) values ('United Arab Emirates');
insert into country (country_name) values ('Portugal');
insert into country (country_name) values ('Poland');
insert into country (country_name) values ('Denmark');

insert into city (city_name, country_id) values ('Belén de Umbría', 10);
insert into city (city_name, country_id) values ('Alīgūdarz', 17);
insert into city (city_name, country_id) values ('Baohe', 23);
insert into city (city_name, country_id) values ('Qidi', 17);
insert into city (city_name, country_id) values ('Shamkhor', 7);
insert into city (city_name, country_id) values ('Krajan Tengah', 5);
insert into city (city_name, country_id) values ('Lizhuang', 23);
insert into city (city_name, country_id) values ('Belleville', 30);
insert into city (city_name, country_id) values ('Крушево', 27);
insert into city (city_name, country_id) values ('Pakham', 2);
insert into city (city_name, country_id) values ('Sohag', 28);
insert into city (city_name, country_id) values ('Hancheng', 12);
insert into city (city_name, country_id) values ('Mehar', 26);
insert into city (city_name, country_id) values ('Linxi', 16);
insert into city (city_name, country_id) values ('São Sebastião do Caí', 16);
insert into city (city_name, country_id) values ('Banjar Desa', 4);
insert into city (city_name, country_id) values ('Shikhany', 21);
insert into city (city_name, country_id) values ('Sofádes', 15);
insert into city (city_name, country_id) values ('Pärnu', 3);
insert into city (city_name, country_id) values ('Buchou', 13);
insert into city (city_name, country_id) values ('Nine', 27);
insert into city (city_name, country_id) values ('Rydzyna', 16);
insert into city (city_name, country_id) values ('Banarankrajan', 29);
insert into city (city_name, country_id) values ('Changchi', 5);
insert into city (city_name, country_id) values ('Blantyre', 28);
insert into city (city_name, country_id) values ('Shuangfeng', 3);
insert into city (city_name, country_id) values ('Oss', 14);
insert into city (city_name, country_id) values ('Lingkou', 5);
insert into city (city_name, country_id) values ('Niterói', 7);
insert into city (city_name, country_id) values ('Cikulina', 18);
insert into city (city_name, country_id) values ('Jiaocheng', 18);
insert into city (city_name, country_id) values ('Zakhim', 25);
insert into city (city_name, country_id) values ('Espanola', 14);
insert into city (city_name, country_id) values ('Kajaani', 25);
insert into city (city_name, country_id) values ('Silodakon', 25);
insert into city (city_name, country_id) values ('Lumil', 10);
insert into city (city_name, country_id) values ('Mina de São Domingos', 1);
insert into city (city_name, country_id) values ('Qingshan', 17);
insert into city (city_name, country_id) values ('Neuzina', 22);
insert into city (city_name, country_id) values ('Maniowy', 28);
insert into city (city_name, country_id) values ('Bay Roberts', 11);
insert into city (city_name, country_id) values ('Oshnavīyeh', 1);
insert into city (city_name, country_id) values ('Karangmangu', 17);
insert into city (city_name, country_id) values ('Siwa Oasis', 22);
insert into city (city_name, country_id) values ('Pital', 12);
insert into city (city_name, country_id) values ('Shilong', 22);
insert into city (city_name, country_id) values ('Haitou', 14);
insert into city (city_name, country_id) values ('Koten', 9);
insert into city (city_name, country_id) values ('Āzādshahr', 16);
insert into city (city_name, country_id) values ('Bébédja', 1);
insert into city (city_name, country_id) values ('København', 18);
insert into city (city_name, country_id) values ('Lille', 16);
insert into city (city_name, country_id) values ('Hujra', 30);
insert into city (city_name, country_id) values ('Zhumadian', 21);
insert into city (city_name, country_id) values ('Reston', 27);
insert into city (city_name, country_id) values ('Saku', 10);
insert into city (city_name, country_id) values ('Batas Barat', 20);
insert into city (city_name, country_id) values ('Kafr Kannā', 10);
insert into city (city_name, country_id) values ('Sukarama', 17);
insert into city (city_name, country_id) values ('Karangbenda', 22);
insert into city (city_name, country_id) values ('Balibago', 23);
insert into city (city_name, country_id) values ('Abang', 20);
insert into city (city_name, country_id) values ('Jalapa', 5);
insert into city (city_name, country_id) values ('Sanli', 10);
insert into city (city_name, country_id) values ('Tatebal', 10);
insert into city (city_name, country_id) values ('Naḩḩālīn', 1);
insert into city (city_name, country_id) values ('Minshan', 6);
insert into city (city_name, country_id) values ('Thorold', 20);
insert into city (city_name, country_id) values ('Kabir', 27);
insert into city (city_name, country_id) values ('Ivanteyevka', 15);
insert into city (city_name, country_id) values ('Tayabo', 19);
insert into city (city_name, country_id) values ('Chengdong', 14);
insert into city (city_name, country_id) values ('Zuogaiduoma', 3);
insert into city (city_name, country_id) values ('Mosteiró', 7);
insert into city (city_name, country_id) values ('Cergy-Pontoise', 11);
insert into city (city_name, country_id) values ('Vaudreuil-Dorion', 11);
insert into city (city_name, country_id) values ('Aghavnatun', 10);
insert into city (city_name, country_id) values ('Damatou', 22);
insert into city (city_name, country_id) values ('Adamstown', 19);
insert into city (city_name, country_id) values ('Maxu', 27);
insert into city (city_name, country_id) values ('Tourcoing', 8);
insert into city (city_name, country_id) values ('Itaguaí', 6);
insert into city (city_name, country_id) values ('Kertasari', 29);
insert into city (city_name, country_id) values ('Iraquara', 17);
insert into city (city_name, country_id) values ('Kushtia', 23);
insert into city (city_name, country_id) values ('Tirana', 9);
insert into city (city_name, country_id) values ('La Laja', 29);
insert into city (city_name, country_id) values ('Brikcha', 19);
insert into city (city_name, country_id) values ('Zushi', 9);
insert into city (city_name, country_id) values ('Kiritsy', 30);
insert into city (city_name, country_id) values ('Shiquan', 18);
insert into city (city_name, country_id) values ('Tanjungpecinan Utara', 7);
insert into city (city_name, country_id) values ('Quma', 17);
insert into city (city_name, country_id) values ('Köln', 18);
insert into city (city_name, country_id) values ('Lazaro Cardenas', 12);
insert into city (city_name, country_id) values ('Mirovice', 9);
insert into city (city_name, country_id) values ('Neglasari', 7);
insert into city (city_name, country_id) values ('Zhugentan', 12);
insert into city (city_name, country_id) values ('Obryte', 24);
insert into city (city_name, country_id) values ('Punkaharju', 26);

insert into address (street, postal_code, door_number, city_id) values ('Anthes', '7648-311', 1187, 42);
insert into address (street, postal_code, door_number, city_id) values ('Coleman', '3054-243', 1, 58);
insert into address (street, postal_code, door_number, city_id) values ('La Follette', '3186-575', 856, 15);
insert into address (street, postal_code, door_number, city_id) values ('Hovde', '6353-130', 1514, 50);
insert into address (street, postal_code, door_number, city_id) values ('Emmet', '8813-916', 1343, 98);
insert into address (street, postal_code, door_number, city_id) values ('Rowland', '2220-517', 744, 4);
insert into address (street, postal_code, door_number, city_id) values ('Packers', '0676-120', 75, 88);
insert into address (street, postal_code, door_number, city_id) values ('Park Meadow', '5186-561', 1816, 61);
insert into address (street, postal_code, door_number, city_id) values ('Schmedeman', '5757-220', 1175, 12);
insert into address (street, postal_code, door_number, city_id) values ('Eggendart', '3699-665', 1788, 22);
insert into address (street, postal_code, door_number, city_id) values ('Oxford', '5164-801', 267, 71);
insert into address (street, postal_code, door_number, city_id) values ('Maple Wood', '5549-001', 558, 31);
insert into address (street, postal_code, door_number, city_id) values ('Cody', '5142-188', 426, 17);
insert into address (street, postal_code, door_number, city_id) values ('Carberry', '8046-705', 998, 61);
insert into address (street, postal_code, door_number, city_id) values ('Dryden', '7578-675', 1816, 49);
insert into address (street, postal_code, door_number, city_id) values ('Blaine', '5728-384', 859, 88);
insert into address (street, postal_code, door_number, city_id) values ('Emmet', '0980-716', 1190, 87);
insert into address (street, postal_code, door_number, city_id) values ('Mayer', '1548-862', 763, 90);
insert into address (street, postal_code, door_number, city_id) values ('Shasta', '9317-217', 732, 51);
insert into address (street, postal_code, door_number, city_id) values ('Huxley', '4663-927', 1369, 36);
insert into address (street, postal_code, door_number, city_id) values ('Buena Vista', '9788-199', 1345, 4);
insert into address (street, postal_code, door_number, city_id) values ('Grayhawk', '9467-246', 150, 21);
insert into address (street, postal_code, door_number, city_id) values ('Katie', '0199-597', 119, 31);
insert into address (street, postal_code, door_number, city_id) values ('Nobel', '9139-943', 81, 30);
insert into address (street, postal_code, door_number, city_id) values ('Florence', '0776-762', 1046, 31);
insert into address (street, postal_code, door_number, city_id) values ('Vera', '0050-421', 1251, 92);
insert into address (street, postal_code, door_number, city_id) values ('Jenna', '3374-864', 733, 99);
insert into address (street, postal_code, door_number, city_id) values ('Waubesa', '7607-194', 687, 14);
insert into address (street, postal_code, door_number, city_id) values ('Oak', '3848-460', 921, 22);
insert into address (street, postal_code, door_number, city_id) values ('Forster', '7363-293', 474, 97);
insert into address (street, postal_code, door_number, city_id) values ('Riverside', '2277-758', 1345, 14);
insert into address (street, postal_code, door_number, city_id) values ('Bultman', '2108-951', 1458, 88);
insert into address (street, postal_code, door_number, city_id) values ('Cambridge', '2798-646', 1992, 74);
insert into address (street, postal_code, door_number, city_id) values ('Eagan', '1665-454', 1430, 13);
insert into address (street, postal_code, door_number, city_id) values ('Wayridge', '4507-394', 484, 77);
insert into address (street, postal_code, door_number, city_id) values ('Hoepker', '7379-927', 1434, 89);
insert into address (street, postal_code, door_number, city_id) values ('Cambridge', '8327-223', 847, 26);
insert into address (street, postal_code, door_number, city_id) values ('Shasta', '6172-716', 1652, 91);
insert into address (street, postal_code, door_number, city_id) values ('Mallard', '3170-854', 405, 37);
insert into address (street, postal_code, door_number, city_id) values ('Buena Vista', '1990-436', 730, 86);
insert into address (street, postal_code, door_number, city_id) values ('Golf Course', '8733-504', 884, 68);
insert into address (street, postal_code, door_number, city_id) values ('Melrose', '9346-837', 669, 52);
insert into address (street, postal_code, door_number, city_id) values ('7th', '1088-370', 202, 37);
insert into address (street, postal_code, door_number, city_id) values ('Nobel', '6300-681', 1953, 51);
insert into address (street, postal_code, door_number, city_id) values ('Golf Course', '5768-964', 1133, 63);
insert into address (street, postal_code, door_number, city_id) values ('Towne', '9479-563', 1382, 47);
insert into address (street, postal_code, door_number, city_id) values ('Everett', '1323-101', 1201, 54);
insert into address (street, postal_code, door_number, city_id) values ('Tony', '7743-761', 1306, 43);
insert into address (street, postal_code, door_number, city_id) values ('Browning', '8366-685', 869, 65);
insert into address (street, postal_code, door_number, city_id) values ('Sunfield', '7433-631', 1615, 50);
insert into address (street, postal_code, door_number, city_id) values ('Forster', '1300-099', 1964, 23);
insert into address (street, postal_code, door_number, city_id) values ('Straubel', '9338-619', 195, 51);
insert into address (street, postal_code, door_number, city_id) values ('2nd', '9919-757', 1542, 3);
insert into address (street, postal_code, door_number, city_id) values ('Ludington', '7835-610', 604, 80);
insert into address (street, postal_code, door_number, city_id) values ('Steensland', '3960-127', 950, 8);
insert into address (street, postal_code, door_number, city_id) values ('Village', '3230-984', 982, 12);
insert into address (street, postal_code, door_number, city_id) values ('Bayside', '7489-547', 1888, 60);
insert into address (street, postal_code, door_number, city_id) values ('Sheridan', '5308-784', 1028, 88);
insert into address (street, postal_code, door_number, city_id) values ('Fisk', '5157-261', 1509, 25);
insert into address (street, postal_code, door_number, city_id) values ('Delladonna', '4746-397', 960, 46);
insert into address (street, postal_code, door_number, city_id) values ('Cambridge', '4517-675', 1690, 30);
insert into address (street, postal_code, door_number, city_id) values ('Thierer', '7168-103', 955, 99);
insert into address (street, postal_code, door_number, city_id) values ('Clarendon', '7589-105', 1080, 76);
insert into address (street, postal_code, door_number, city_id) values ('Larry', '3577-588', 633, 58);
insert into address (street, postal_code, door_number, city_id) values ('Union', '7151-826', 1276, 47);
insert into address (street, postal_code, door_number, city_id) values ('Sheridan', '5748-897', 165, 93);
insert into address (street, postal_code, door_number, city_id) values ('Nobel', '7585-273', 1800, 93);
insert into address (street, postal_code, door_number, city_id) values ('Derek', '9944-004', 673, 48);
insert into address (street, postal_code, door_number, city_id) values ('Cody', '8636-723', 1668, 43);
insert into address (street, postal_code, door_number, city_id) values ('Fordem', '6096-077', 717, 2);
insert into address (street, postal_code, door_number, city_id) values ('Mallory', '5975-907', 1069, 58);
insert into address (street, postal_code, door_number, city_id) values ('Debra', '9190-004', 681, 42);
insert into address (street, postal_code, door_number, city_id) values ('Buhler', '6050-268', 780, 72);
insert into address (street, postal_code, door_number, city_id) values ('Delladonna', '3464-623', 988, 98);
insert into address (street, postal_code, door_number, city_id) values ('Shopko', '0711-433', 1344, 60);
insert into address (street, postal_code, door_number, city_id) values ('Towne', '4049-822', 338, 96);
insert into address (street, postal_code, door_number, city_id) values ('Buell', '3479-339', 1264, 9);
insert into address (street, postal_code, door_number, city_id) values ('Myrtle', '9605-662', 284, 48);
insert into address (street, postal_code, door_number, city_id) values ('Haas', '1930-419', 410, 66);
insert into address (street, postal_code, door_number, city_id) values ('Vahlen', '2619-471', 296, 69);
insert into address (street, postal_code, door_number, city_id) values ('Glendale', '9549-289', 1391, 84);
insert into address (street, postal_code, door_number, city_id) values ('Shoshone', '7087-522', 545, 52);
insert into address (street, postal_code, door_number, city_id) values ('Del Mar', '1348-437', 1947, 80);
insert into address (street, postal_code, door_number, city_id) values ('Harbort', '0812-190', 685, 88);
insert into address (street, postal_code, door_number, city_id) values ('Pearson', '8540-836', 528, 94);
insert into address (street, postal_code, door_number, city_id) values ('Memorial', '4714-716', 534, 77);
insert into address (street, postal_code, door_number, city_id) values ('Maywood', '9395-541', 755, 73);
insert into address (street, postal_code, door_number, city_id) values ('Lighthouse Bay', '7860-733', 1553, 83);
insert into address (street, postal_code, door_number, city_id) values ('Towne', '7355-978', 1190, 9);
insert into address (street, postal_code, door_number, city_id) values ('Namekagon', '5527-961', 891, 13);
insert into address (street, postal_code, door_number, city_id) values ('Prairieview', '0516-842', 657, 76);
insert into address (street, postal_code, door_number, city_id) values ('Badeau', '5833-401', 881, 31);
insert into address (street, postal_code, door_number, city_id) values ('Meadow Vale', '8544-979', 672, 32);
insert into address (street, postal_code, door_number, city_id) values ('Shoshone', '4706-963', 1842, 14);
insert into address (street, postal_code, door_number, city_id) values ('Londonderry', '1106-466', 1142, 13);
insert into address (street, postal_code, door_number, city_id) values ('Prairie Rose', '8025-741', 1527, 80);
insert into address (street, postal_code, door_number, city_id) values ('Dwight', '3780-211', 126, 97);
insert into address (street, postal_code, door_number, city_id) values ('Blue Bill Park', '5761-158', 1117, 52);
insert into address (street, postal_code, door_number, city_id) values ('Surrey', '7176-809', 865, 33);
insert into address (street, postal_code, door_number, city_id) values ('Nobel', '0568-401', 1045, 87);

